### ISSUE TITLE
How to retrieve all SeekCues 

### ISSUE THREAD

**Issue by Ivshti** [oeuillot/node-matroska#1]
@oeuillot  - great work! This is mighty fast!

I couldn't figure out how to get a list of all the seekcues though, as I cannot figure out the API yet. I tried traversing through .children. I ended up with an object that prints to

```
         87#17    * Seek  children[size=17]
        90#18      * SeekID  b[4]=1c53bb6b => Cues
        97#19      * SeekPosition  u[4]=3331491650
```

But I couldn't figure out a way to get a full list of all seek queues in the mkv

Thanks in advance!

**Comment by oeuillot** [comment]
Hello !

Watch the document1.js, you will find an example to list segments, you can add the same thing for Seek !  (And propose a pull request)

I am on holiday, I am back in one week !

Best,

**Comment by Ivshti** [comment]
Thanks, I already figured it out - check this out - https://github.com/Ivshti/retrieve-keyframes/blob/master/index.js
